const data={
    posts:[
        {
            id:1,
            post:"./welcome-message.jpg",
            name:"Prakash",
            profile:"./krishna.jpg",
            desc:"nice post",
            tags:[
                "#nature",
                "#moments",
                "travel"
            ]
        },
        {
            id:2,
            post:"./DSC_0056.JPG",
            name:"Sajid",
            profile:"./iron.jpg",
            desc:"college",
            tags:[
                "#fest",
                "#college",
            ]
        },
        {
            id:3,
            post:"./krishna.jpg",
            name:"Surya",
            profile:"./DSC_0065.JPG",
            desc:"Krishna",
            tags:[
                "#devote",
                "#krishna",
            ]
        },
        {
            id:4,
            post:"./iron.jpg",
            name:"Surya",
            profile:"./DSC_0065.JPG",
            desc:"ironman",
            tags:[
                "#college",
                "#moments",
            ]
        },
    ]
}
module.exports = data;